In [1]:
import numpy as np
import pandas as pd
import random as rd

In [4]:
hand = np.random.randint(low=2, high = 11, size =13)
print(hand)

[ 5  2  2  7  6  6  3  3  3 10  5  9  6]


In [40]:
dealer_card_val = [2,3,4,5,6,7,8,9,10, 10, 10, 10, 11]
dealer_aces = [0,0,0,0,0,0,0,0,0, 0,0,0,1]
print(dealer_card_val, "\n", dealer_aces)

[2, 3, 4, 5, 6, 7, 8, 9, 10, 10, 10, 10, 11] 
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


In [17]:
rd.choice(dealer_card_val)

9

In [46]:
dealer_hand_running_total = np.array(dealer_card_val)
print (dealer_hand_running_total)

[ 2  3  4  5  6  7  8  9 10 10 10 10 11]


In [42]:
np.random.choice(dealer_card_val,13)

array([10, 10, 10,  2, 11,  4,  8,  4, 10,  6, 10,  7, 11])

In [48]:
round_2_dealer_hand = dealer_hand_running_total + np.random.choice(dealer_card_val,13)
print(round_2_dealer_hand)

[12 10 14 12 11 16 16 14 19 20 20 14 21]


In [54]:
dealer_hand_running_total

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 10, 10, 10, 11])

In [55]:
round_2_dealer_hand

array([12, 10, 14, 12, 11, 16, 16, 14, 19, 20, 20, 14, 21])

In [85]:
round_3_dehand = np.zeros(13)

for i in range(13):
    if round_2_dealer_hand[i] >= 17:
        round_3_dehand[i] = round_2_dealer_hand[i]
    else:
        round_3_dehand[i] = round_2_dealer_hand[i] + np.random.choice(dealer_card_val,1)
print (round_3_dehand)


[18. 20. 25. 22. 21. 22. 18. 24. 19. 20. 20. 21. 21.]


In [82]:
who

a	 dealer_aces	 dealer_card_val	 dealer_hand_running_total	 hand	 i	 np	 pd	 rd	 
round_2_dealer_hand	 round_3_dehand	 


In [86]:
type (dealer_hand_running_total)

numpy.ndarray

In [113]:
dealer_hand_running_total =np.zeros(13) 
dealer_hand_running_total = np.array(dealer_card_val)#initial card
dealer_hand_running_total = np.array(dealer_card_val) + np.random.choice(dealer_card_val,13)#2 cards

dealer_hand_running_total = np.array([12, 13,  7, 22,  8, 17, 14, 17, 22, 18, 20, 20, 16])

for i in range(13): #chagning the aces to 1 if two aces
    if dealer_hand_running_total[i] == 22:
        dealer_hand_running_total[i] = 12

twist_1 = 1 #set flag for looping for new cards if 1 card is below 17

while twist_1 == 1:
    twist_1 =0
    for i in range(13):
        if dealer_hand_running_total[i] < 17:
            dealer_hand_running_total[i] = dealer_hand_running_total[i] + np.random.choice(dealer_card_val,1)
            if dealer_hand_running_total[i] <17:
                twist_1 = 1


print(dealer_hand_running_total)

[18 26 21 20 18 17 24 17 22 18 20 20 18]


In [99]:
cheese =np.array ([12, 1, 7, 15, 8, 17])

In [100]:
cheese

array([12,  1,  7, 15,  8, 17])

In [ ]:
dealer_hand_running_total_2 = 0 
dealer_hand_running_total_2 = np.random.choice(dealer_card_val)#2 cards

dealer_hand_running_total = np.array([12, 13,  7, 22,  8, 17, 14, 17, 22, 18, 20, 20, 16])

for i in range(13): #chagning the aces to 1 if two aces
    if dealer_hand_running_total[i] == 22:
        dealer_hand_running_total[i] = 12

twist_1 = 1 #set flag for looping for new cards if 1 card is below 17

while twist_1 == 1:
    twist_1 =0
    for i in range(13):
        if dealer_hand_running_total[i] < 17:
            dealer_hand_running_total[i] = dealer_hand_running_total[i] + np.random.choice(dealer_card_val,1)
            if dealer_hand_running_total[i] <17:
                twist_1 = 1


print(dealer_hand_running_total)

In [276]:
dealer_card_val_poss = [2,3,4,5,6,7,8,9,10, 10, 10, 10, 11]
dealer_card_val_poss_1_ten = [2,3,4,5,6,7,8,9,10, 11]

num_card = {}

for x in range(2,12):
    if x == 10:
        num_card["card{0}".format(x)]=16
    else:
        num_card["card{0}".format(x)]=4


for proba_cards in range(2,12):
    if proba_cards ==10:
        proba_cards.append(4/52)
    else:
        proba_cards.append(1/52)
        
proba_cards = [two/cards_left, thr/cards_left, fou/cards_left, fiv/13, six/13, sev/13, eig/13, nin/13, ten/13, ace/13 ]

def deal_likely_hand(dealer_card_val_2):
    aces = 0
    aces_as_1 =0
    
    if dealer_card_val_2 == 11:
        aces +=1
    #print(dealer_card_val_2)

    new_card = np.random.choice(dealer_card_val_poss)
    if new_card == 11:
        aces +=1

    if aces == 2:
        dealer_hand_running_total_2 =12
        aces_as_1 = 1
    else:
        dealer_hand_running_total_2 = dealer_card_val_2 + new_card  #2 cards

    #print(new_card, dealer_hand_running_total_2)

    twist_1 =1 
    while twist_1 == 1:
        twist_1 = 0
        if dealer_hand_running_total_2 < 17:
                dealer_hand_running_total_2 = dealer_hand_running_total_2 + np.random.choice(dealer_card_val_poss)
                #print(dealer_hand_running_total_2)            
                if dealer_hand_running_total_2 <17:
                    twist_1 = 1
                if dealer_hand_running_total_2 > 21 and aces - aces_as_1 > 0:
                    dealer_hand_running_total_2 = dealer_hand_running_total_2 - 10
                    aces_as_1 += 1
                    if dealer_hand_running_total_2 <17:
                        twist_1 = 1

    #print(aces)
    return dealer_hand_running_total_2

n_sims = 1000

#dealer_card_val_2 = np.random.choice(dealer_card_val_poss)
results_per = np.zeros((10,8))
for u in range(10):
    results_per[u,0] = dealer_card_val_poss_1_ten[u] #fill the first column with the possible 1st card values 
#for dealer_card_val_2 in dealer_card_val_poss_1_ten:
    #print(dealer_card_val_poss_1_ten[u])
    bust = 0
    s17s = 0
    s18s = 0
    s19s = 0
    s20s = 0
    s21s = 0
    for p in range (n_sims):    
        result_deal = deal_likely_hand(dealer_card_val_poss_1_ten[u])
        if result_deal >21:
            bust += 1
        elif result_deal == 17:
            s17s +=1
        elif result_deal == 18:
            s18s +=1
        elif result_deal == 19:
            s19s +=1
        elif result_deal == 20:
            s20s +=1
        elif result_deal == 21:
            s21s +=1
    results_per[u,1] = s17s
    results_per[u,2] = s18s
    results_per[u,3] = s19s
    results_per[u,4] = s20s
    results_per[u,5] = s21s
    results_per[u,6] = bust   
    results_per[u,7] = s17s + s18s + s19s + s20s + s21s + bust
    #print("busted ", bust/n_sims *100, "%") / #print("17s ", s17s/n_sims *100, "%") #print("18s ", s18s/n_sims *100, "%")
    #print("19s ", s19s/n_sims *100, "%") / print("20s ", s20s/n_sims *100, "%")/ print("21s ", s21s/n_sims *100, "%")
    
print (results_per)
    

[[   2.  115.  133.  127.  117.  106.  402. 1000.]
 [   3.  124.  119.  123.  105.  100.  429. 1000.]
 [   4.  141.  117.  121.  108.   91.  422. 1000.]
 [   5.  117.  127.   98.  116.   94.  448. 1000.]
 [   6.  135.   85.  119.   92.   90.  479. 1000.]
 [   7.  356.  126.   91.   58.   66.  303. 1000.]
 [   8.  124.  395.  119.   51.   58.  253. 1000.]
 [   9.  113.  118.  348.  121.   60.  240. 1000.]
 [  10.   91.  111.  117.  356.   92.  233. 1000.]
 [  11.  126.  145.  124.  112.  357.  136. 1000.]]


In [5]:
#results_per_2 = ([(   2,  115,  133,  127,  117,  106,  402, 1000),
 (   3,  124,  119,  123,  105,  100,  429, 1000),
 (   4,  141,  117,  121,  108,   91,  422, 1000),
 (   5,  117,  127,   98,  116,   94,  448, 1000),
 (   6,  135,   85,  119,   92,   90,  479, 1000),
 (   7,  356,  126,   91,   58,   66,  303, 1000),
 (   8,  124,  395,  119,   51,   58,  253, 1000),
 (   9,  113,  118,  348,  121,   60,  240, 1000),
 (  10,   91,  111,  117,  356,   92,  233, 1000),
 (  11,  126,  145,  124,  112,  357,  136, 1000)])

In [5]:
#results_per_2

In [289]:
player_total = 19
dealer_card_val_2 = 9
mat_pos_deal = dealer_card_val_2 - 2

#result_deal = deal_likely_hand(dealer_card_val_2

if player_total <18: #always twist as dealer is less than 50% likely to bust and hence will have 17-21 beating player on 17 or less
    twist = "yes"

if player_total == 18: #dealer wins with 18,19,20,21 (posn 2,3,4,5) or 1- bust, 17 posn 0,6
    if results_per[mat_pos_deal,1] + results_per[mat_pos_deal,6] < 500:
        twist ="yes"
    else:
        twist = "no"
        
if player_total == 19: #dealer wins with 19,20,21 (posn 3,4,5)
    if results_per[mat_pos_deal,3] + results_per[mat_pos_deal,4] + results_per[mat_pos_deal,5] >= 500:
        twist ="yes" 
    else:
        twist = "no"

if player_total == 20: #dealer wins with 20,21 (posn 3,4,5)
    if results_per[mat_pos_deal,4] + results_per[mat_pos_deal,5] >= 500:
        twist ="yes"
    else:
        twist  "no"

if player_total == 21: #dealer wins with 21 (posn 4,5)
    twist = "no"

#dealer_card_val_2 = np.random.choice(dealer_card_val_poss)

#print(result_deal)
print (twist)
#print (player_total)

529.0
yes


In [253]:
a = np.zeros((10,6))

In [258]:
a[2,3] = 6
print(a)

[[0. 0. 0. 6. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 6. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [263]:
results_per = np.zeros((10,6))
for u in range(10):
    results_per[u,0] = dealer_card_val_poss_1_ten[u]

In [264]:
results_per

array([[ 2.,  0.,  0.,  0.,  0.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0.],
       [ 4.,  0.,  0.,  0.,  0.,  0.],
       [ 5.,  0.,  0.,  0.,  0.,  0.],
       [ 6.,  0.,  0.,  0.,  0.,  0.],
       [ 7.,  0.,  0.,  0.,  0.,  0.],
       [ 8.,  0.,  0.,  0.,  0.,  0.],
       [ 9.,  0.,  0.,  0.,  0.,  0.],
       [10.,  0.,  0.,  0.,  0.,  0.],
       [11.,  0.,  0.,  0.,  0.,  0.]])

In [3]:
np.array([(1,2,3),(4,5,6)])

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
results_per_2 = np.array([(   2,  115,  133,  127,  117,  106,  402, 1000),
 (   3,  124,  119,  123,  105,  100,  429, 1000),
 (   4,  141,  117,  121,  108,   91,  422, 1000),
 (   5,  117,  127,   98,  116,   94,  448, 1000),
 (   6,  135,   85,  119,   92,   90,  479, 1000),
 (   7,  356,  126,   91,   58,   66,  303, 1000),
 (   8,  124,  395,  119,   51,   58,  253, 1000),
 (   9,  113,  118,  348,  121,   60,  240, 1000),
 (  10,   91,  111,  117,  356,   92,  233, 1000),
 (  11,  126,  145,  124,  112,  357,  136, 1000)])

In [8]:
results_per_2

array([[   2,  115,  133,  127,  117,  106,  402, 1000],
       [   3,  124,  119,  123,  105,  100,  429, 1000],
       [   4,  141,  117,  121,  108,   91,  422, 1000],
       [   5,  117,  127,   98,  116,   94,  448, 1000],
       [   6,  135,   85,  119,   92,   90,  479, 1000],
       [   7,  356,  126,   91,   58,   66,  303, 1000],
       [   8,  124,  395,  119,   51,   58,  253, 1000],
       [   9,  113,  118,  348,  121,   60,  240, 1000],
       [  10,   91,  111,  117,  356,   92,  233, 1000],
       [  11,  126,  145,  124,  112,  357,  136, 1000]])

In [4]:
[1/13, 1/13]

[0.07692307692307693, 0.07692307692307693]

In [22]:
num_card = {}
for x in range(2,12):
    if x == 10:
        num_card["card{0}".format(x)]=16
    else:
        num_card["card{0}".format(x)]=4
num_card

{'card2': 4,
 'card3': 4,
 'card4': 4,
 'card5': 4,
 'card6': 4,
 'card7': 4,
 'card8': 4,
 'card9': 4,
 'card10': 16,
 'card11': 4}

In [25]:
new_card1 = 8
num_card["card{0}".format(new_card1)] = num_card["card{0}".format(new_card1)] -1
num_card

{'card2': 4,
 'card3': 4,
 'card4': 4,
 'card5': 4,
 'card6': 4,
 'card7': 4,
 'card8': 3,
 'card9': 4,
 'card10': 16,
 'card11': 4}

In [28]:
kl = [5,5,5]

In [29]:
kl

[5, 5, 5]

In [36]:
k2 =[]
for x in range(1,12):
    k2.append(4/52)

In [37]:
k2

[0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693]

In [38]:
len(k2)

11

In [57]:
num_card = {}

cards_left = 52

for x in range(2,12):
    if x == 10:
        num_card["card{0}".format(x)]=16
    else:
        num_card["card{0}".format(x)]=4
num_card#["card{0}".format(9)]

{'card2': 4,
 'card3': 4,
 'card4': 4,
 'card5': 4,
 'card6': 4,
 'card7': 4,
 'card8': 4,
 'card9': 4,
 'card10': 16,
 'card11': 4}

In [58]:
proba_cards = []
 
for x in range(2,12):
    proba_cards.append(num_card["card{0}".format(x)]/cards_left)
        
proba_cards

[0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.07692307692307693,
 0.3076923076923077,
 0.07692307692307693]

In [50]:
k = []
k.append(4)
k.append(6)
print(k)
k =[]
k.append(2)
k.append(1)
k

[4, 6]


[2, 1]